### ISSUE TITLE
This vs Laravel/Lumen

### ISSUE THREAD

**Issue by richarddewit** [luminancephp/framework#1]
Just out of curiosity, why should I pick this over Laravel (or Lumen)?

**Comment by michaelgv** [comment]
Luminance is a micro framework, it mostly could compare to Lumen.

The goals we had in mind are simple:

- Fast performance 

- Simple and clean structure 

- Multiple router strategy, you can route magically or pre-defined, without a complex structure 

- You're not limited by any templating engines, or any complex plugin system, etc. - you can implement anything you want, for example, you want Twig? Just composer require, it'll update the composer autoloader, and you're ready out of the box

- Elegant and simplified ORM Table class, with no limitations

Ultimately, why you should pick this over Laravel or Lumen? 

If you're looking for a micro framework, with fast performance and the freedom and flexibility to choose exactly what you want and need versus what's required, you're in good hands with Luminance.

Luminance spawned from an internal framework I've been using for projects in production for three years, and recently got upgraded to PHP 7 by myself, and is in production on four of my business websites. My largest usage of Luminance is an API backend for an iOS and Android, it handles about 150 requests per minute.

**Comment by richarddewit** [comment]
Good explanation!

**Comment by michaelgv** [comment]
Thanks :)
